// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// shuffle_mat
arma::mat shuffle_mat(arma::mat inmat);
RcppExport SEXP _EloRating_extension_shuffle_mat(SEXP inmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type inmat(inmatSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_mat(inmat));
    return rcpp_result_gen;
END_RCPP
}
// order_by_ds
arma::mat order_by_ds(arma::mat mat);
RcppExport SEXP _EloRating_extension_order_by_ds(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(order_by_ds(mat));
    return rcpp_result_gen;
END_RCPP
}
// make_rank_matrix
arma::mat make_rank_matrix(arma::mat mat);
RcppExport SEXP _EloRating_extension_make_rank_matrix(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(make_rank_matrix(mat));
    return rcpp_result_gen;
END_RCPP
}
// get_c
double get_c(arma::mat inmat, arma::mat rankdistmat);
RcppExport SEXP _EloRating_extension_get_c(SEXP inmatSEXP, SEXP rankdistmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type inmat(inmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rankdistmat(rankdistmatSEXP);
    rcpp_result_gen = Rcpp::wrap(get_c(inmat, rankdistmat));
    return rcpp_result_gen;
END_RCPP
}
// csteep
List csteep(arma::mat inmat, int nrand);
RcppExport SEXP _EloRating_extension_csteep(SEXP inmatSEXP, SEXP nrandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type inmat(inmatSEXP);
    Rcpp::traits::input_parameter< int >::type nrand(nrandSEXP);
    rcpp_result_gen = Rcpp::wrap(csteep(inmat, nrand));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EloRating_extension_shuffle_mat", (DL_FUNC) &_EloRating_extension_shuffle_mat, 1},
    {"_EloRating_extension_order_by_ds", (DL_FUNC) &_EloRating_extension_order_by_ds, 1},
    {"_EloRating_extension_make_rank_matrix", (DL_FUNC) &_EloRating_extension_make_rank_matrix, 1},
    {"_EloRating_extension_get_c", (DL_FUNC) &_EloRating_extension_get_c, 2},
    {"_EloRating_extension_csteep", (DL_FUNC) &_EloRating_extension_csteep, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_EloRating_extension(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
