# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shuffle_mat <- function(inmat) {
    .Call(`_EloRating_extension_shuffle_mat`, inmat)
}

order_by_ds <- function(mat) {
    .Call(`_EloRating_extension_order_by_ds`, mat)
}

make_rank_matrix <- function(mat) {
    .Call(`_EloRating_extension_make_rank_matrix`, mat)
}

get_c <- function(inmat, rankdistmat) {
    .Call(`_EloRating_extension_get_c`, inmat, rankdistmat)
}

csteep <- function(inmat, nrand) {
    .Call(`_EloRating_extension_csteep`, inmat, nrand)
}

